name: Delete Unnecessary Branch
on:
  pull_request:
    types:
      - closed
jobs:
  Create-Pull-Request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with: 
          fetch-depth: 0

      - name: Fetch List Where has Same HEAD
        env: 
          HEAD: ${{ github.event.pull_request.head.ref }}
        # オープンしているPRのうち、Headのブランチ名が一致するPRの件数を取得する
        run: echo count=`gh pr list --state open --head "feature/add-ddd" | wc -l | xargs` >> $GITHUB_ENV

      - name: Delete Branch If Need
        if: env.count == 0
        run: git push --delete origin feature/add-ddd
