name: Push main to sub
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  Trigger-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger!"
      - run: ls -la
  Check-Out:
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with: 
          fetch-depth: 0
      - name: PullRequestParameter
        env: 
          TITLE: ${{ github.event.pull_request.title }}
          BODY: ${{ github.event.pull_request.body }}

        run: |
          echo $TITLE
          echo $BODY
          echo ${{ github.event.pull_request.assignees }}
